import { VegetationIntegers } from "../../api/types";

export const VEGETATION: Map<VegetationIntegers, string> = new Map()

VEGETATION.set(0, 'Savannah')
VEGETATION.set(1, 'Mountain 1')
VEGETATION.set(2, 'Snow')
VEGETATION.set(3, 'Swamp')
VEGETATION.set(4, 'Desert 1')
VEGETATION.set(5, 'Water')
VEGETATION.set(6, 'Buildable water')
VEGETATION.set(7, 'Desert 2')
VEGETATION.set(8, 'Meadow 1')
VEGETATION.set(9, 'Meadow 2')
VEGETATION.set(10, 'Meadow 3')
VEGETATION.set(11, 'Mountain 2')
VEGETATION.set(12, 'Mountain 3')
VEGETATION.set(13, 'Mountain 4')
VEGETATION.set(14, 'Steppe')
VEGETATION.set(15, 'Flower meadow')
VEGETATION.set(16, 'Lava 1')
VEGETATION.set(17, 'Magenta')
VEGETATION.set(18, 'Mountain meadow')
VEGETATION.set(19, 'Water (not used by ships)')
VEGETATION.set(20, 'Lava 2 / Magenta')
VEGETATION.set(21, 'Lava 3 / Magenta')
VEGETATION.set(22, 'Lava 4 / Magenta')
VEGETATION.set(23, 'Buildable mountain 2')
