import { AnyBuilding } from './api'

export type Filename = string

const prefix = "assets/roman-buildings/"

const houseImageMap: Map<AnyBuilding, Filename> = new Map()
const houseUnderConstructionImageMap: Map<AnyBuilding, Filename> = new Map()

houseImageMap.set("Armory", prefix + "armory.png")
houseImageMap.set("Bakery", prefix + "bakery.png")
houseImageMap.set("Barracks", prefix + "barracks.png")
houseImageMap.set("Brewery", prefix + "brewery.png")
houseImageMap.set("Catapult", prefix + "catapult.png")
houseImageMap.set("CoalMine", prefix + "coal-mine.png")
houseImageMap.set("DonkeyFarm", prefix + "donkey-breeder.png")
houseImageMap.set("Farm", prefix + "farm.png")
houseImageMap.set("Fishery", prefix + "fishery.png")
houseImageMap.set("ForesterHut", prefix + "forester-hut.png")
houseImageMap.set("Fortress", prefix + "fortress.png")
houseImageMap.set("GoldMine", prefix + "gold-mine.png")
houseImageMap.set("GraniteMine", prefix + "granite-mine.png")
houseImageMap.set("GuardHouse", prefix + "guardhouse.png")
houseImageMap.set("Headquarter", prefix + "headquarter.png")
houseImageMap.set("HunterHut", prefix + "hunter-hut.png")
houseImageMap.set("IronMine", prefix + "iron-mine.png")
houseImageMap.set("IronSmelter", prefix + "iron-smelter.png")
houseImageMap.set("Mill", prefix + "mill-no-fan.png")
houseImageMap.set("Mint", prefix + "mint.png")
houseImageMap.set("PigFarm", prefix + "pig-farm.png")
houseImageMap.set("Quarry", prefix + "quarry.png")
houseImageMap.set("Sawmill", prefix + "sawmill.png")
houseImageMap.set("SlaughterHouse", prefix + "slaughter-house.png")
houseImageMap.set("WatchTower", prefix + "watchtower.png")
houseImageMap.set("Well", prefix + "well.png")
houseImageMap.set("Woodcutter", prefix + "woodcutter.png")
houseImageMap.set("Harbor", prefix + "harbor.png")
houseImageMap.set("LookoutTower", prefix + "lookout-tower.png")
houseImageMap.set("Metalworks", prefix + "metalworks.png")
houseImageMap.set("Shipyard", prefix + "shipyard.png")
houseImageMap.set("Storehouse", prefix + "storehouse.png")

houseUnderConstructionImageMap.set("Armory", prefix + "armory-under-construction.png")
houseUnderConstructionImageMap.set("Bakery", prefix + "bakery-under-construction.png")
houseUnderConstructionImageMap.set("Barracks", prefix + "barracks-under-construction.png")
houseUnderConstructionImageMap.set("Brewery", prefix + "brewery-under-construction.png")
houseUnderConstructionImageMap.set("Catapult", prefix + "catapult-under-construction.png")
houseUnderConstructionImageMap.set("CoalMine", prefix + "coal-mine-under-construction.png")
houseUnderConstructionImageMap.set("DonkeyFarm", prefix + "donkey-breeder-under-construction.png")
houseUnderConstructionImageMap.set("Farm", prefix + "farm-under-construction.png")
houseUnderConstructionImageMap.set("Fishery", prefix + "fishery-under-construction.png")
houseUnderConstructionImageMap.set("ForesterHut", prefix + "forester-hut-under-construction.png")
houseUnderConstructionImageMap.set("Fortress", prefix + "fortress-under-construction.png")
houseUnderConstructionImageMap.set("GoldMine", prefix + "gold-mine-under-construction.png")
houseUnderConstructionImageMap.set("GraniteMine", prefix + "granite-mine-under-construction.png")
houseUnderConstructionImageMap.set("GuardHouse", prefix + "guardhouse-under-construction.png")
houseUnderConstructionImageMap.set("HunterHut", prefix + "hunter-hut-under-construction.png")
houseUnderConstructionImageMap.set("IronMine", prefix + "iron-mine-under-construction.png")
houseUnderConstructionImageMap.set("IronSmelter", prefix + "iron-smelter-under-construction.png")
houseUnderConstructionImageMap.set("Mill", prefix + "mill-no-fan-under-construction.png")
houseUnderConstructionImageMap.set("Mint", prefix + "mint-under-construction.png")
houseUnderConstructionImageMap.set("PigFarm", prefix + "pig-farm-under-construction.png")
houseUnderConstructionImageMap.set("Quarry", prefix + "quarry-under-construction.png")
houseUnderConstructionImageMap.set("Sawmill", prefix + "sawmill-under-construction.png")
houseUnderConstructionImageMap.set("SlaughterHouse", prefix + "slaughter-house-under-construction.png")
houseUnderConstructionImageMap.set("WatchTower", prefix + "watchtower-under-construction.png")
houseUnderConstructionImageMap.set("Well", prefix + "well-under-construction.png")
houseUnderConstructionImageMap.set("Woodcutter", prefix + "woodcutter-under-construction.png")
houseUnderConstructionImageMap.set("Harbor", prefix + "harbor-under-construction.png")
houseUnderConstructionImageMap.set("LookoutTower", prefix + "lookout-tower-under-construction.png")
houseUnderConstructionImageMap.set("Metalworks", prefix + "metalworks-under-construction.png")
houseUnderConstructionImageMap.set("Shipyard", prefix + "shipyard-under-construction.png")
houseUnderConstructionImageMap.set("Storehouse", prefix + "storehouse-under-construction.png")


export { houseImageMap, houseUnderConstructionImageMap }
