let houseImageMap = {
    Bakery:         "bakery-small.png",
    ForesterHut:    "house.png",
    Woodcutter:     "house.png",
    Well:           "well-with-tree-small.png",
    Quarry:         "house.png",
    Barracks:       "barracks-small.png",
    GuardHouse:     "house.png",
    HunterHut:      "house.png",
    Fishery:        "house.png",
    GoldMine:       "house.png",
    IronMine:       "house.png",
    CoalMine:       "house.png",
    GraniteMine:    "house.png",
    Sawmill:        "sawmill-small.png",
    WatchTower:     "house.png",
    Mill:           "house.png",
    Mint:           "house.png",
    SlaughterHouse: "house.png",
    Catapult:       "house.png",
    Headquarter:    "headquarter-small.png",
    Farm:           "house.png",
    PigFarm:        "house.png",
    DonkeyFarm:     "house.png",
    Fortress:       "fortress-small.png",
    Brewery:        "house.png",
    Armory:         "house.png"
};

export default houseImageMap;
